name: Artifact Release

on:
        workflow_dispatch:
                inputs:
                        tag:
                                description: "Release tag (v#.#.#)"
                                type: string
                                required: true
        push:
                tags:
                        - "v*"

permissions:
        contents: write

jobs:
        release-dispatch:
                if: inputs.tag != ''
                uses: opentffoundation/scripts/.github/workflows/release.yml@main
                with:
                        tag: ${{ inputs.tag }}
                secrets:
                        GH_PAT: ${{ secrets.GH_PAT }}
                        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
                        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

        release-push:
                if: inputs.tag == ''
                uses: opentffoundation/scripts/.github/workflows/release.yml@main
                with:
                        tag: ${{ github.ref_name }}
                secrets: inherit
